### ISSUE TITLE
Release for Jupyterlab 1.0

### ISSUE THREAD

**Issue by xhochy** [jupyterhub/jupyter-server-proxy#139]
It seems that support for Jupyterlab 1.0 was already implemented but not released. Would it be possible to get a release for this?

**Comment by juliusvonkohout** [comment]
+1 i think
@yuvipanda @betatim @ian-r-rose @quasiben @ryanlovett have commit rights and therefore most likely the pypi and npm credentials.

**Comment by tlkh** [comment]
This is a great useful extension. Hope one of the maintainers can publish it soon! Meanwhile I think installing via the dev method works.

**Comment by dirkcgrunwald** [comment]
How are you getting the dev install to work with JupyterLab?

I'm building a customized datascience-notebook build and use jupyterlab-server-proxy to install the VScode from coding.com ( see https://github.com/dirkcgrunwald/jupyter_codeserver_proxy- )

However, when I try to install the labextension, I'm running into a version incompatability.

My install is done using:

```                                                                                                        
RUN     (cd /tmp ; git clone https://github.com/jupyterhub/jupyter-server-proxy.git ) && \                       
        ( cd /tmp/jupyter-server-proxy ; pip install . )     
```

and the error I'm seeing is

```
Step 68/88 : RUN        jupyter labextension install jupyterlab-server-proxy                                     
 ---> Running in a0de2edbc36c                                                                                    
An error occured.                                                                                                
ValueError: This extension does not yet support the current version of JupyterLab.                               
                                                                                                                 
                                                                                                                 
Conflicting Dependencies:                                                                                        
JupyterLab              Extension      Package                                                                   
>=1.0.2 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/application                                                  
>=1.0.2 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/launcher                                                     
See the log file for details:  /tmp/jupyterlab-debug-43awzidr.log                                                
The command '/bin/sh -c jupyter labextension install jupyterlab-server-proxy' returned a non-zero code: 1  
```

**Comment by tlkh** [comment]
Here's the method I used (extracted from my Dockerfile):

```dockerfile
RUN ...
    #jupyter labextension install jupyterlab-server-proxy && \
    cd /tmp/ && \
    git clone --depth 1 https://github.com/jupyterhub/jupyter-server-proxy && \
    cd jupyter-server-proxy/jupyterlab-server-proxy && \
    npm install && npm run build && jupyter labextension link . && \
    npm run build && jupyter lab build && \
    ...
```

**Comment by mathematicalmichael** [comment]
@tlkh thanks! that worked for me!!

**Comment by ian-r-rose** [comment]
Ping @yuvipanda, can you add a few of us to the npm owners for the JupyterLab extension?

**Comment by dirkcgrunwald** [comment]
Btw, I was recently able to rebuild my notebook using the hacks below; I'm building the jupyterlab proxy from source

RUN     pip install -vvv git+git://github.com/jupyterhub/jupyter-server-prox\
y@master && \                                                                
        jupyter serverextension enable --py --sys-prefix jupyter_server_prox\
y                                                                            
                                                                             
RUN     (cd /tmp && \                                                        
        git clone https://github.com/jupyterhub/jupyter-server-proxy && \    
        cd /tmp/jupyter-server-proxy/jupyterlab-server-proxy && \            
        npm install && npm run build && jupyter labextension link . )        
                                                                             
#RUN                                                                         
#       jupyter labextension install jupyterlab-server-proxy                 
                                                                             
RUN     pip install --index-url https://test.pypi.org/simple/ --extra-index-\
url https://pypi.org/simple jupyter-codeserver-proxy==1.0b1                  
                                                                             
RUN     cd /opt && \                                                         
        mkdir /opt/code-server && \                                          
        cd /opt/code-server && \                                             
        wget -qO- https://github.com/cdr/code-server/releases/download/2.pre\
view.11-vsc1.37.0/code-server2.preview.11-vsc1.37.0-linux-x86_64.tar.gz | ta\
r zxvf - --strip-components=1                                                
                                                                             
#       wget -qO- https://github.com/cdr/code-server/releases/download/1.111\
9-vsc1.33.1/code-server1.1119-vsc1.33.1-linux-x64.tar.gz | tar zxvf - --stri\
p-components=1                                                               
                                                                             
ENV     PATH=/opt/code-server:$PATH

**Comment by albertmichaelj** [comment]
I'd just like to second that a release would be super helpful! I need the X-Forward stuff at https://github.com/jupyterhub/jupyter-server-proxy/commit/50e0358372adfb993d1795436a409f68e472e6bb for a Spark use case. I can build from source, but it would be great to not have to.

**Comment by ian-r-rose** [comment]
@albertmichaelj I think the X-Forward stuff you need should be in the most recent Python release. This issue is about the JupyterLab extension (which is a nice-to-have, but not critical to the actual functionality of the package).

**Comment by albertmichaelj** [comment]
Your right, it is! It is the last commit (save for the version bump) in the last release. My bad! I'm still getting some weird behavior, but it may be unrelated.

**Comment by saulshanabrook** [comment]
If anyone wants a workaround, I published the master branch on my own package: `jupyter labextension install jupyterlab-server-proxy-saulshanabrook`. I am happy to publish this one as well if anyone wants to give me access to the NPM package.

**Comment by blink1073** [comment]
Fixed in #159

**Comment by saulshanabrook** [comment]
Thanks @blink1073!

**Comment by juliusvonkohout** [comment]
it is not fixed. the python package is still not at 2.x https://pypi.org/project/jupyter-server-proxy/

**Comment by ryanlovett** [comment]
@juliusvonkohout I think the python and npm packages don't need to have the same version string, but I could be wrong.

**Comment by consideRatio** [comment]
I'll go ahead and close this as the original issue is closed and I've personally used this python package and jupyterlab extension with JupyterLab 1.

The steps I've successfully used are

```
pip install jupyter-server-proxy
jupyter labextension install @jupyterlab/server-proxy
```
